---
- name: Instalando o pip
  apt: 
    name: 
      - python3-pip
      - python-setuptools
      - python3-setuptools

- name: Instalando dependências do módulo do k8s
  pip: 
    name: 
      - openshift
      - PyYAML

- name: Copiando o arquivo de deployment da App para o host
  template: 
    src: app-v1.yml.j2
    dest: "{{ app_path_v1 }}"
    owner: root
    group: root
    mode: '0644'
  register: copiando_deploy_app_v1

- name: Copiando o arquivo de deployment da App V2 para o host
  template: 
    src: app-v2.yml.j2
    dest: "{{ app_path_v2 }}"
    owner: root
    group: root
    mode: '0644'
  register: copiando_deploy_app_v2

- name: Deploy da app-v2
  k8s:
    state: present
    namespace: default
    src: "{{ app_path_v2 }}"

- name: Scale down da app-v1
  k8s:
    state: present
    namespace: default
    src: "{{ app_path_v1 }}"

- name: Dentro de 02 minutos o app-v1 será removido. Pressione ctrl + c para cancelar
  pause: 
    minutes: 2

- name: Removendo o app-v1
  k8s:
    state: absent
    src: "{{ app_path_v1 }}"